service: blitz-tools

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: us-east-2
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
      Resource: 
          - "arn:aws:dynamodb:us-east-2:668320536571:table/blitz-api"
          - "arn:aws:dynamodb:us-east-2:668320536571:table/collectionAggregateData"

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: GET
          cors: true
      - http:
          path: /collections
          method: GET
          cors: true
      - http:
          path: /collections/{symbol}
          method: GET
          cors: true
      - http:
          path: /collectionAggregateData
          method: GET
          cors: true
      - http:
          path: /collectionAggregateData/{symbol}
          method: GET
          cors: true
  #collectionsHandler:
  #  handler: src/seed.handler
  #  timeout: 45
  #  events:
      # Invoke Lambda function every 10 minutes
      # - schedule: rate(10 minutes)