service: blitz-tools

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: us-east-2
  stage: prod
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
      Resource: 
          - "arn:aws:dynamodb:us-east-2:668320536571:table/blitz-api"
          - "arn:aws:dynamodb:us-east-2:668320536571:table/collectionAggregateData"

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: GET
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true